### ISSUE TITLE
Update Text Concatenation to Multiline String Templates

### ISSUE THREAD

**Issue by jboelen** [chrismeono1022/Notifier#12]
https://stackoverflow.com/a/36074215

```ruby
"%{foo} %{bar}" % {foo: 'baz', bar: 'quux'}
#=> "baz quux"
```

**Comment by chrismeono1022** [comment]
Will keep string interpolation because some of the interpolated strings are numbers followed by % sign and it can look kind of messy. I did do away with string concatenation, thank you 🙏
