### ISSUE TITLE
Move Date Formatting to Utility

### ISSUE THREAD

**Issue by jboelen** [chrismeono1022/Notifier#8]
https://github.com/chrismeono1022/Notifier/blob/e9dd49d5fedee1b426cc695d60d1f8ed672c8630/covid_report.rb#L32
https://github.com/chrismeono1022/Notifier/blob/e9dd49d5fedee1b426cc695d60d1f8ed672c8630/covid_report.rb#L56

**Comment by chrismeono1022** [comment]
PR https://github.com/chrismeono1022/Notifier/pull/14 addressed this but forgot to tag.
